<%@ include file="dbconnect.jsp" %>
<core:remove var="firstname"/>
<core:remove var="middletname"/>
<core:remove var="lastname"/>
<core:remove var="guardians"/>
<core:remove var="dob"/>
<core:remove var="gender"/>
<core:remove var="contact"/>
<core:remove var="add1"/>
<core:remove var="add2"/>
<core:remove var="district" />
<core:remove var="state"/>
<core:remove var="country"/>
<core:remove var="pincode" />
<core:remove var="instid"/>
<core:remove var="instname"/>
<core:remove var="doj"/>
<core:remove var="selectedModule"/>
<core:remove var="listbranch"/>
<core:remove var="sem"/>
<core:remove var="AccType"/>
<core:remove var="terms" />